### ISSUE TITLE
SM doesn't work in Rails 3

### ISSUE THREAD

**Issue by fakingfantastic** [fhwang/sample_models#1]
Right out of the box: https://gist.github.com/671712

I'm gonna see what I can do to help get it up to speed

**Comment by fhwang** [comment]
So the newest gem, 1.1.0, should work for Rails 3. Please try it out and let me know how it goes.

**Comment by fhwang** [comment]
I'm going to close this--if you're seeing specific issues with Rails 3 please feel free to open new issues.

**Comment by fakingfantastic** [comment]
Yeah - close it up, I'm banging away in R3 now
