### ISSUE TITLE
Can't find who defines the validation method validates_email_format_of 

### ISSUE THREAD

**Issue by FotoVerite** [fhwang/sample_models#3]
Fails if you don't have the plugin installed

**Comment by fakingfantastic** [comment]
Yeah, I'm +1-ing this. I added sample_models to an early R3 project, ran my passing test - and I get that error right out of the gate. Looks like you are hard coding :validates_email_format_of into the validations_to_intercept array: I'm gonna try to add that in only if the plugin is found. Patch to come...

**Comment by fhwang** [comment]
This is now fixed in the most recent version -- please update the gem and try again. Thanks!
